### ISSUE TITLE
Switch the default branch from "trunk" to "main"

### ISSUE THREAD

**Issue by jessitron** [gracefuldev/sixmilebridge#18]
heroku doesn't actually deploy unless it's on one of those branches.

it's probably possible to override that, but it is not worth it. Avdi declares defeat and agrees we shall conform to the new standard.

**Comment by jessitron** [comment]
OK, updated on github and circle. @avdi all that remains is for you to switch over your copy before you forget and push the old branch again.

**Comment by avdi** [comment]
Done
